export type { NavLink, NavbarData } from './navbar'
export type { HeroTitle, HeroLink, HeroCta, HeroPhoto, HeroStat, HeroData } from './hero'
export type { SpecialtyItem, SpecialtiesData } from './specialties'
export type { SpecialtyFaq, SpecialtyDetailItem, SpecialtyDetailData } from './specialtyDetail'
export type { PrivacyBlock, PrivacySection, PrivacyData } from './privacy'
export type { ProfileBadge, ProfileCredential, ProfileTitle, ProfileCta, ProfileData } from './profile'
export type { ProcessStep, ProcessData } from './process'
export type { TestimonialData, TestimonialItem, TestimonialTitle } from './testimonials'
export type { ContactData, ContactForm, ContactWhatsApp, ContactReassurance, ContactDetail, ContactSchema, ContactSchemaAddress, ContactSchemaHours } from './contact'
export type { FooterData, FooterLink, FooterSocial, FooterColumn } from './footer'